version: '2'
services:
  application:
    container_name: kylin
    image: apachekylin/apache-kylin-standalone:kylin-4.0.1-mondrian
    ports:
      - "7070:7070"
      - "7080:7080"
      - "2181:2181"
      - "8042:8042"
      - "8032:8032"
      - "50070:50070"
      - "8088:8088"
    expose:
      - "7070"
      - "7080"
    restart: always